# Generated by Django 4.0.3 on 2023-12-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salesperson',
            new_name='Salesrep',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='salesperson',
            new_name='salesrep',
        ),
    ]
