# Generated by Django 4.0.3 on 2023-12-21 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_salesperson_salesrep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales_rest.autovo', unique=True),
        ),
    ]
