# Generated by Django 4.0.3 on 2023-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_sale_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='autovo',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
