# Generated by Django 4.0.3 on 2023-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='technincian',
            new_name='technician',
        ),
    ]
