# Generated by Django 4.0.3 on 2023-12-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_technincian_appointment_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileVO',
            fields=[
                ('autovo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_rest.autovo')),
            ],
            bases=('service_rest.autovo',),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('finished', 'finished')], default='scheduled', max_length=20),
        ),
    ]
