# Generated by Django 4.0.3 on 2023-12-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_automobilevo_alter_appointment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomobileVO',
        ),
    ]
